name: Deploy to Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run deployment script
        run: |
          python deploy.py
